version: '{build}'
install:
  - ps: Invoke-WebRequest http://kitcreator.rkeene.org/kits/ae78c6ebb1cca64104a326db1be0110e8b2457c9/tclkit.exe -OutFile tclkit.exe
  - cmd: cd .. && git clone https://github.com/tclssg/packer && cd tclssg
build_script:
  - cmd: tclkit.exe appveyor.tcl
test_script:
  - cmd: tclkit.exe tests.tcl
artifacts:
  - path: artifacts\*
